---
- name: gather facts
  hosts: bastion

- name: Deploy & setup vault server files
  hosts: vault_server
  collections:
    - aventus.avn_vault

  roles:
  - role: avn-vault-infra
    when: deploy_vault|bool
    become: yes
  - role: vault-init
    when: init_vault|bool
    become: yes
  - role: avn-vault-setup
    when: setup_avn_vault|bool
  # - role: create-account-from-seed
