---
- name: gather facts
  hosts: bastion

- name: Deploy & setup vault server files
  hosts: vault_server

  roles:
  - role: aventus.ansible-avn-vault
    when: deploy_vault|bool
    become: yes
  - role: vault-init
    when: init_vault|bool
    become: yes
  - role: avn-vault-setup
    when: setup_avn_vault|bool
