aws-for-fluent-bit:
  serviceAccount:
    create: false
    name: fluent-bit
    
  input:
    skipLongLines: On
    refreshInterval: 10
    memBufLimit: 5MB
    parser: docker
    db: /fluent-bit/state/flb_cwagent.db
    path: /var/log/containers/*.log
    tag: application.*

  cloudWatch:
    enabled: true
    region: eu-west-1
    logRetentionDays: 30
    autoCreateGroup: true
    logFormat: json/emf
  
  kinesis:
    enabled: false
  
  firehose:
    enabled: false
  
  elasticsearch:
    enabled: false
