pipeline {
    agent {
        docker { image 'node:16' }
    }
    environment {
        NPM_CONFIG_CACHE = "${WORKSPACE}/.npm"
        UAT_USER_SEED = credentials('uat_gateway_tests_user_seed')
        PUBLIC_TESTNET_USER_SEED = credentials('public_testnet_gateway_tests_user_seed')
        SECRET_UAT_ACCOUNTS_FILE = credentials('uat_avn_gateway_tests_accounts')
        SECRET_UAT_ENVIRONMENT_FILE = credentials('uat_avn_gateway_tests_environment')
        SECRET_PUBLIC_TESTNET_ACCOUNTS_FILE = credentials('public_testnet_avn_gateway_tests_accounts')
        SECRET_PUBLIC_TESTNET_ENVIRONMENT_FILE = credentials('public_testnet_avn_gateway_tests_environment')
        GOOGLE_DRIVE_SERVICE_ACCOUNT_KEY = credentials('google_drive_service_account_key');
        GOOGLE_DRIVE_SHARED_DRIVE_ID = credentials('google_drive_shared_drive_id');
        SLACK_WEBHOOK_URL = credentials('slack_webhook_url');
        SCHEDULED_TESTS_GITHUB_CREDS = credentials('scheduled_tests_github_creds');
    }
    triggers {
        cron('0 0 * * *')
    }
    parameters {
        choice(name: 'Chain', choices: ['uat', 'public_testnet'], description: 'Choose which chain to test');
        choice(name: 'Test', choices: ['All', 'configurationTests', 'accountFunding', 'apiOffline', 'accessTests', 'awtTest', 'utilsTest', 'pollApiTest', 'proxyApiTest', 'queryApiTest', 'sendApiTest', 'relayerFees', 'splitFees', 'stakingTests', 'remoteSignerTests'], description: 'Choose which test to run');
        string(name: 'Descriptive_name', defaultValue: '', description: 'Give a descriptive name to your test run');
    }
    stages {
        stage('Build') {
            steps {
                sh 'rm -rf node_modules'
                sh 'rm -f package-lock.json'
                sh 'npm cache clean --force'
                sh "npm install git+https://${SCHEDULED_TESTS_GITHUB_CREDS}@github.com/Aventus-Network-Services/avn-lib-slackTestNotifications.git"
                sh "npm install git+https://${SCHEDULED_TESTS_GITHUB_CREDS}@github.com/Aventus-Network-Services/avn-lib-googleDriveUploadService.git"
                sh 'npm install'
                sh 'npm install avn-api'
                sh 'npm install --save-dev mochawesome'
                sh 'npm install mochawesome-merge --save-dev'
                script {
                    if (params.Chain == 'uat') {
                        env.ACCOUNTS = env.SECRET_UAT_ACCOUNTS_FILE
                        env.ENVIRONMENT = env.SECRET_UAT_ENVIRONMENT_FILE
                        // env.AVN_SURI = env.UAT_USER_SEED
                    } else if (params.Chain == 'public_testnet') {
                        env.ACCOUNTS = env.SECRET_PUBLIC_TESTNET_ACCOUNTS_FILE
                        env.ENVIRONMENT = env.SECRET_PUBLIC_TESTNET_ENVIRONMENT_FILE
                        // env.AVN_SURI = env.PUBLIC_TESTNET_USER_SEED
                    } else {
                        sh 'echo "No chain selected"'
                    }
                }
            }
        }
        stage('Gateway tests') {
            steps {
                script {
                    if(params.Test != 'All') {
                        echo "Running ${params.Test} test on ${params.chain}"
                        sh "npm run ${params.Test} ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT}"
                        return
                    } else {
                        echo "Running all tests on ${params.chain}"
                        // Add stages for running all tests
                        stage('Account Funding') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run accountFunding ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accountFundingReport;"
                            }
                        }

                        script {
                            def parallelStages = [
                                'awtTest',
                                'configurationTests'
                            ]

                            def parallelConfig = [:]

                            parallelStages.each { stageName ->
                                parallelConfig["${stageName}"] = {
                                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                        script {
                                            sh "npm run ${stageName.replaceAll(' ', '')} ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=${stageName.replaceAll(' ', '')}Report;"
                                        }
                                    }
                                }
                            }

                            parallel parallelConfig
                        }


                        // stage('Parallel tests') {
                        //     parallel {}
                        //         stage('Gateway Api: apiOffline Test') {
                        //             steps {
                        //                 catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        //                     script {
                        //                         sh "npm run apiOffline ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=apiOfflineReport;"
                        //                     }
                        //                 }
                        //             }

                        //         }
                        //         stage('Gateway Api: configuration Test') {
                        //             steps {
                        //                 catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        //                     script {
                        //                         sh "npm run configurationTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=configurationReport;"
                        //                     }
                        //                 }
                        //             }
                        //         }
                                // stage('Gateway Api: Awt Test') {
                                //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                //         sh "npm run awtTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=awtReport;"
                                //     }
                                // }
                                // stage('Gateway Api: Utils') {
                                //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                //         sh "npm run utilsTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=utilsReport;"
                                //     }
                                // }
                                // stage('Gateway Api: Poll') {
                                //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                //         sh "npm run pollApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=pollApiReport;"
                                //     }
                                // }
                                // stage('Gateway Api: Query') {
                                //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                //         sh "npm run queryApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=queryApiReport;"
                                //     }
                                // }
                                // stage('Gateway Api: relayerFees') {
                                //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                //         sh "npm run relayerFees ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=relayerFeesReport;"
                                //     }
                                // }
                        //     }
                        // }
                        stage('Gateway Api: remoteSignerTests') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run remoteSignerTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=queryApiReport;"
                            }
                        }
                        // stage('Gateway Api: Access') {
                        //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        //         sh "npm run accessTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accessReport;"
                        //     }
                        // }
                        // stage('Gateway Api: splitFees') {
                        //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        //         sh "npm run splitFees ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accessReport;"
                        //     }
                        // }
                        // stage('Gateway Api: Send') {
                        //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        //         sh "npm run sendApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=sendApiReport;"
                        //     }
                        // }
                        // stage('Gateway Api: Proxy') {
                        //     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        //         sh "npm run proxyApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=proxyApiReport;"
                        //     }
                        // }
                    }
                }
            }
        }
    }
}

