pipeline {
    agent {
        docker { image 'node:16' }
    }
    environment {
        NPM_CONFIG_CACHE = "${WORKSPACE}/.npm"
        UAT_USER_SEED = credentials('uat_gateway_tests_user_seed')
        PUBLIC_TESTNET_USER_SEED = credentials('public_testnet_gateway_tests_user_seed')
        SECRET_UAT_ACCOUNTS_FILE = credentials('uat_avn_gateway_tests_accounts')
        SECRET_UAT_ENVIRONMENT_FILE = credentials('uat_avn_gateway_tests_environment')
        SECRET_PUBLIC_TESTNET_ACCOUNTS_FILE = credentials('public_testnet_avn_gateway_tests_accounts')
        SECRET_PUBLIC_TESTNET_ENVIRONMENT_FILE = credentials('public_testnet_avn_gateway_tests_environment')
        GOOGLE_DRIVE_SERVICE_ACCOUNT_KEY = credentials('google_drive_service_account_key');
        GOOGLE_DRIVE_SHARED_DRIVE_ID = credentials('google_drive_shared_drive_id');
        SLACK_WEBHOOK_URL = credentials('slack_webhook_url');
        SCHEDULED_TESTS_GITHUB_CREDS = credentials('scheduled_tests_github_creds');
    }
    triggers {
        cron('0 0 * * *')
    }
    parameters {
        string(name: 'Report_name', defaultValue: '', description: 'Give a descriptive name to your test run');
        choice(name: 'Chain', choices: ['uat', 'public_testnet', 'vow'], description: 'Choose which chain to test');
        booleanParam(name: 'All', defaultValue: false, description: 'Run all tests');
        booleanParam(name: 'configurationTests', defaultValue: false);
        booleanParam(name: 'apiOffline', defaultValue: false);
        booleanParam(name: 'accessTests', defaultValue: false);
        booleanParam(name: 'awtTest', defaultValue: false);
        booleanParam(name: 'utilsTest', defaultValue: false);
        booleanParam(name: 'pollApiTest', defaultValue: false);
        booleanParam(name: 'proxyApiTest', defaultValue: false);
        booleanParam(name: 'queryApiTest', defaultValue: false);
        booleanParam(name: 'sendApiTest', defaultValue: false);
        booleanParam(name: 'relayerFees', defaultValue: false);
        booleanParam(name: 'splitFees', defaultValue: false);
        booleanParam(name: 'remoteSignerTests', defaultValue: false);
        booleanParam(name: 'stakingTests', defaultValue: false);
    }
    stages {
        stage('Build') {
            steps {
                sh 'rm -rf node_modules'
                sh 'rm -f package-lock.json'
                sh 'npm cache clean --force'
                sh "npm install git+https://${SCHEDULED_TESTS_GITHUB_CREDS}@github.com/Aventus-Network-Services/avn-lib-slackTestNotifications.git"
                sh "npm install git+https://${SCHEDULED_TESTS_GITHUB_CREDS}@github.com/Aventus-Network-Services/avn-lib-googleDriveUploadService.git"
                sh 'npm install'
                sh 'npm install avn-api'
                sh 'npm install --save-dev mochawesome'
                sh 'npm install mochawesome-merge --save-dev'
                script {
                    if (params.Chain == 'uat') {
                        env.ACCOUNTS = env.SECRET_UAT_ACCOUNTS_FILE
                        env.ENVIRONMENT = env.SECRET_UAT_ENVIRONMENT_FILE
                    } else if (params.Chain == 'public_testnet') {
                        env.ACCOUNTS = env.SECRET_PUBLIC_TESTNET_ACCOUNTS_FILE
                        env.ENVIRONMENT = env.SECRET_PUBLIC_TESTNET_ENVIRONMENT_FILE
                    } else {
                        sh 'echo "No chain selected"'
                    }
                }
            }
        }
        stage('Gateway tests') {
            steps {
                script {
                    if(!params.All) {
                        stage('Account Funding') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run accountFunding ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accountFundingReport;"
                            }
                        }
                        if (params.remoteSignerTests) {
                            stage('Gateway Api: remoteSignerTests') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run remoteSignerTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=remoteSignerTestsReport;"
                                }
                            }
                        }
                        if (params.accessTests) {
                            stage('Gateway Api: Access') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run accessTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accessReport;"
                                }
                            }
                        }
                        if (params.apiOffline) {
                            stage('Gateway Api: apiOffline') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run apiOffline ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=apiOfflineReport;"
                                }
                            }
                        }
                        if (params.awtTest) {
                            stage('Gateway Api: awtTest') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run awtTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=awtTestReport;"
                                }
                            }
                        }
                        if (params.utilsTest) {
                            stage('Gateway Api: utilsTest') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run utilsTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=utilsTestReport;"
                                }
                            }
                        }
                        if (params.pollApiTest) {
                            stage('Gateway Api: pollApiTest') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run pollApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=pollApiTestReport;"
                                }
                            }
                        }
                        if (params.proxyApiTest) {
                            stage('Gateway Api: proxyApiTest') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run proxyApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=proxyApiTestReport;"
                                }
                            }
                        }
                        if (params.queryApiTest) {
                            stage('Gateway Api: queryApiTest') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run queryApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=queryApiTestReport;"
                                }
                            }
                        }
                        if (params.sendApiTest) {
                            stage('Gateway Api: sendApiTest') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run sendApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=sendApiTestReport;"
                                }
                            }
                        }
                        if (params.relayerFees) {
                            stage('Gateway Api: relayerFees') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run relayerFees ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=relayerFeesReport;"
                                }
                            }
                        }
                        if (params.splitFees) {
                            stage('Gateway Api: splitFees') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run splitFees ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=splitFeesReport;"
                                }
                            }
                        }
                        if (params.stakingTests) {
                            stage('Gateway Api: stakingTests') {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh "npm run stakingTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=stakingTestsReport;"
                                }
                            }
                        }
                    } else {
                        echo "Running all tests on ${params.chain}"
                        stage('Account Funding') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run accountFunding ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accountFundingReport;"
                            }
                        }
                        script {
                            def parallelStages = [
                                'awtTest',
                                'configurationTests',
                                'apiOffline',
                                'utilsTest',
                                'pollApiTest',
                                'relayerFees'
                            ]
                            def parallelConfig = [:]
                            parallelStages.each { stageName ->
                                parallelConfig["${stageName}"] = {
                                    stage("${stageName}") {
                                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                            script {
                                                sh "npm run ${stageName.replaceAll(' ', '')} ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=${stageName.replaceAll(' ', '')}Report;"
                                            }
                                        }
                                    }
                                }
                            }
                            parallel parallelConfig
                        }
                        stage('Gateway Api: remoteSignerTests') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run remoteSignerTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=queryApiReport;"
                            }
                        }
                        stage('Gateway Api: Access') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run accessTests ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accessReport;"
                            }
                        }
                        stage('Gateway Api: splitFees') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run splitFees ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=accessReport;"
                            }
                        }
                        stage('Gateway Api: Query') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run queryApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=sendApiReport;"
                            }
                        }
                        stage('Gateway Api: Send') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run sendApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=sendApiReport;"
                            }
                        }
                        stage('Gateway Api: Proxy') {
                            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                sh "npm run proxyApiTest ${params.Chain} -- --accounts=${ACCOUNTS} --environment=${ENVIRONMENT} --reporter mochawesome --reporter-options reportDir=reportDir,reportFilename=proxyApiReport;"
                            }
                        }
                    }
                    stage('Generate report') {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            sh "npx mochawesome-merge ./reportDir/*.json -o finalReport.json"
                            sh "npx mochawesome-report-generator finalReport.json --reportDir ./ --inline"
                            sh "npm run upload ${params.Chain} -- --test_descriptive=${params.Descriptive_name}"
                            sh "npm run slack ${params.Chain}"
                        }
                    }
                }
            }
        }
    }
}

