---

- name: Get app-role login token
  uri:
    url: '{{ api_addr_value }}/v1/auth/approle/login'
    method: POST
    return_content: yes
    headers:
      Content-Type: application/json
      X-Vault-Request: true
    body: '{"role_id":"{{ role_id }}","secret_id":"{{ secret_id }}"}'
    body_format: json
  register: login_response

- set_fact: token="{{ login_response.content | from_json | json_query('auth.client_token')}}"

- name: Create SS58 account from existing seed
  uri:
    url: '{{ api_addr_value }}/v1/avn-vault/user/set/{{ new_account_SS58 }}'
    method: POST
    headers:
      Content-Type: application/json
      X-Vault-Request: true
      X-Vault-Token: '{{ token }}'
    body: '{ "name": "{{ new_account_SS58 }}", "seed": "{{ new_account_seed }}" }'
    status_code: 200
    body_format: json
