{{- $environment := printf "files/.env.%s" .Values.environment -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  {{- .Files.Get $environment | toString | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  VAULT_URL: https://vault.{{ .Values.environment }}.avn-gateway.aventus.io:8200/v1/