apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      serviceAccount: avn-connector
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repo }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: server
              containerPort: {{ .Values.deployment.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          env:
            - name: NODE_ENV
              value: docker
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: DOCUMENT_DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: server
            - name: MONGO_SERVER
              value: $(DOCUMENT_DB_ADDRESS):27017/?ssl=true
            - name: MQ_BROKER_AMQP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials
                  key: server
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}