apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      serviceAccount: avn-connector
      {{- if and (not (eq .Values.environment "mainnet")) (not (eq .Values.environment "testnet"))}}
      initContainers:
        - name: relayer
          image: "189013141504.dkr.ecr.eu-west-2.amazonaws.com/gateway-api/relayer:latest"
          command: ["node", "scripts/addRelayer.js", "setRelayer", "-u", "$(RELAYER_ADDRESS)", "-s", "$(RELAYER_SEED)"]
          env:
            # Hardcoded relayers for test environments only, the seed is not sensitive and does not exist in testnet or mainnet.
            - name: RELAYER_ADDRESS
              value: "5FbUQ2kJWLoqHuSTSNNqBwKwdQnBVe4HF3TeGyu6UoZaryTh"
            - name: RELAYER_SEED
              value: "0xa343da434e14c8cef7c474551a63e7e4c0cb4670a2374368ee01e670ab0d2464"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repo }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: server
              containerPort: {{ .Values.deployment.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          env:
            - name: NODE_ENV
              value: docker
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: DOCUMENT_DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: server
            - name: MONGO_SERVER
              value: $(DOCUMENT_DB_ADDRESS):27017/?ssl=true
            - name: MQ_BROKER_AMQP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials
                  key: server
            - name: MQ_SECRET_ARN
              value: arn:aws:secretsmanager:eu-west-1:{{ .Values.accountId }}:secret:rabbitmq
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}