apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      serviceAccount: avn-connector
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repo }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: server
              containerPort: {{ .Values.deployment.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
            - configMapRef:
                name: vault
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}
            {{- if eq .Values.nodeEnv "production" }}
            - name: MQ_BROKER_AMQP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rabbit-credentials
                  key: server
            {{- else }}
            - name: MQ_BROKER_AMQP_ENDPOINT
              value: rabbit-rabbitmq:5672
            - name: MQ_PROTOCOL
              value: amqp
            {{- end }}
            - name: ETHERSCAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: etherscan-credentials
                  key: etherscan_api_key
            - name: INFURA_URL
              valueFrom:
                secretKeyRef:
                  name: infura-credentials
                  key: infura_url
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: gateway_rds_host
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: gateway_app_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: gateway_app_user_password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: gateway_app_database
            - name: DB_SYNC_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: gateway_app_database
            - name: VAULT_APP_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-role
                  key: role-id
            - name: VAULT_APP_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-role
                  key: secret-id
            - name: REDIS_URL
              value: redis.{{ .Values.environment }}.aventus.internal
            - name: MQ_SECRET_ARN
              value: arn:aws:secretsmanager:eu-west-1:{{ .Values.accountId }}:secret:rabbitmq
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
