apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mongo-credentials
spec:
  backendType: secretsManager
  data:
    - key: documentdb
      name: password
      property: password
    - key: documentdb
      name: username
      property: username
    - key: documentdb
      name: server
      property: server
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: etherscan-credentials
spec:
  backendType: secretsManager
  data:
    - key: etherscan
      name: etherscan_api_key
      property: etherscan_api_key
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: infura-credentials
spec:
  backendType: secretsManager
  data:
    - key: infura
      name: infura_url
      property: infura_url

{{- if eq .Values.nodeEnv "production" }}
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rabbit-credentials
spec:
  backendType: secretsManager
  data:
    - key: rabbitmq
      name: server
      property: server
{{- end }}
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: vault-role
spec:
  backendType: secretsManager
  data:
    - key: vault
      name: role-id
      property: app_role_id
    - key: vault
      name: secret-id
      property: app_secret_id
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rds-credentials
spec:
  backendType: secretsManager
  data:
    - key: gateway_rds_logins
      name: gateway_app_user
      property: gateway_app_user
    - key: gateway_rds_logins
      name: gateway_app_database
      property: gateway_app_database
    - key: gateway_rds_logins
      name: gateway_app_user_password
      property: gateway_app_user_password
    - key: gateway_rds_logins
      name: gateway_app_host
      property: gateway_app_host
    - key: gateway_rds_logins
      name: gateway_app_schema_sync
      property: gateway_app_schema_sync