apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mongo-credentials
spec:
  backendType: secretsManager
  data:
    - key: documentdb
      name: password
      property: password
    - key: documentdb
      name: username
      property: username
    - key: documentdb
      name: server
      property: server
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: etherscan-credentials
spec:
  backendType: secretsManager
  data:
    - key: etherscan
      name: etherscan_api_key
      property: etherscan_api_key
{{- if eq .Values.nodeEnv "production" }}
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rabbit-credentials
spec:
  backendType: secretsManager
  data:
    - key: rabbitmq
      name: server
      property: server
{{- end }}
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: vault-role
spec:
  backendType: secretsManager
  data:
    - key: vault
      name: role-id
      property: app_role_id
    - key: vault
      name: secret-id
      property: app_secret_id