apiVersion: v1
kind: ServiceAccount
metadata:
  name: avn-connector
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountId }}:role/k8s-sa-{{ .Release.Namespace }}-avn-connector