const AvnApi = require('../index.js')
const { accounts } = require('../config/accounts.json')
const BN = require('bn.js')
const { hexToU8a, u8aToHex, u8aConcat } = require('@polkadot/util')
var colors = require('colors');
const { TypeRegistry } = require('@polkadot/types')
const { signatureVerify, cryptoWaitReady } = require('@polkadot/util-crypto')
const { Keyring } = require('@polkadot/keyring');
const { assert, expect } = require('chai');
const keyring = new Keyring({ type: 'sr25519', ss58Format: 42 })

const registry = new TypeRegistry();
const SIGNING_CONTEXT = 'awt_gateway_api';

const cbaSet = {
    bashBinary: '\\x3c\\x61\\x77\\x74\\x5f\\x67\\x61\\x74\\x65\\x77\\x61\\x79\\x5f\\x61\\x70\\x69\\xd0\\xbc\\x96\\x2a\\xc2\\x1f\\xb7\\x4c\\xc5\\x08\\x2f\\x24\\xda\\x62\\x26\\x0d\\xc0\\xd4\\x1c\\x12\\x82\\xce\\x46\\xcc\\xef\\xac\\xa6\\xed\\xc5\\xf0\\x0b\\x49\\x60\\x32\\x30\\x32\\x32\\x2d\\x30\\x31\\x2d\\x31\\x30\\x54\\x31\\x36\\x3a\\x30\\x30\\x3a\\x35\\x38\\x2e\\x38\\x35\\x39\\x5a',
    pk: '0xd0bc962ac21fb74cc5082f24da62260dc0d41c1282ce46ccefaca6edc5f00b49',
    iat: '2022-01-10T16:00:58.859Z',
    sig: '0xb07ea03c16ee31d37d9e109cf15bd0aaf8654f51429660565dda52eb516cf24a6343efa76907850d57c5d3baf54bd300c8efad7c0b9249aae7536ee8e9bde081'
}

async function main() {
    await cryptoWaitReady(); // This is essential for successful verification of signatures

    // Remove comments to run specific test as needed:

    // await demoCbaAwt();
    // testSCALEEncoding();
    // testCBASignature();
    testSubkeyCompatibility();
}

async function demoCbaAwt() {
    // Run this script with node ./testTools.js <config file name without extension>
    // If you get an error at startup similar to this
    // TypeError: Cannot read property 'startsWith' of undefined
    // it may be because you have not defined your SURI environment variable
    let args = process.argv.slice(2);
    let configPath = args[0] ? `../config/${args[0]}.json` : '../config/sandbox.json'
    const { gateway } = require(configPath)

    let sender = accounts.cbaTestAccount;
    let api = await init(gateway);

    let iat = cbaSet.iat;
    let pk = sender.publicKey;

    let sigPayload = api.awt.encodeAvnPublicKeyForSigning(pk, iat);
    console.log('\n\nAwt Signature Public Key\n'.blue.bold, pk);
    console.log('\nAwt Signature Payload\n'.red.bold, sigPayload);

    let payload = api.awt.generateAwtPayload(sender.mnemonic, iat);
    let myToken = await api.awt.generateAwtTokenFromPayload(payload);
    console.log('Payload: ', payload)
    console.log('Token %o', myToken);

    console.log('CBA Test. Verifying AwtToken generated by us with CBA data');
    wrapTest(verifyAwtTokenSignature(payload.pk, payload.iat, payload.sig));
}

function testSCALEEncoding() {
    let text1 = 'hello world';
    let text2 = 'hix';

    const payload = u8aConcat(
        registry.createType('Text', text1).toU8a(false),
        registry.createType('Text', text2).toU8a(false)
      )

    console.log('Encoded Payload Test'.green, `${u8aToHex(payload)}`.brightBlue.bold);
}

function testCBASignature() {
    console.log('Verifying Signature created by CBA (using Subkey)'.bold);

    let cbaEncodedData;
    if (cbaSet.bashBinary) {
        cbaEncodedData = bashEscapedToHex(cbaSet.bashBinary);
        console.log(`Reconstructed Hex String binary payload: ${cbaEncodedData}`.magenta);
    } else {
        cbaEncodedData = cbaSet.encodedData;
    }

    let awtToken = {
        "pk": cbaSet.pk,
        "iat": cbaSet.iat,
        "sig": cbaSet.sig
    };

    console.log('Checking signature from AwtToken'.brightMagenta.bold);
    wrapTest(verifyAwtTokenSignature(awtToken.pk, awtToken.iat, awtToken.sig));

    console.log('Checking signature from HexString encoded data'.brightMagenta.bold, cbaEncodedData.brightBlue.bold);
    wrapTest(verifyHexStringSignature(cbaEncodedData, awtToken.pk, awtToken.sig));
}

async function testSubkeyCompatibility() {
    await cryptoWaitReady();

    // let message = 'hello world';
    // let encodedPayload = u8aToHex(registry.createType('Text', message).toU8a(false));
    let signingKey = '0x81cd713ef51940a684b5db9c36dcafc3199b6bdff4b2c332f9fc88a3f69c0881';
    let publicKey = '0x36838287ca3370224054f8a59ac79f112aac88e9adc39fd6b00d1e723e141a31';
    let sig = '0xb2063d62ec83953db52bde27edb8fd88f2f12281ce819b61634363c2fea3a561144f458be399acb0eb5b7faf0a6da12dd88d45a386d99ab1fad188952ef37182';

    /*
    console.log('Verifying Subkey generated signatures');

    console.log('* * * * * * * * *'.yellow);
    // Verification Fails
    console.log('message: hello world. Verified against encoded message');
    wrapTest(verifyBytesSignature(encodedPayload, publicKey, sig));

    // Verification Fails
    console.log('message: hello world. Verified against plain message data');
    wrapTest(verifyBytesSignature(message, publicKey, sig));

    // Succeeds
    console.log('message: hello world. Plain verification against plain message data');
    wrapTest(verifyHexStringSignature(message, publicKey, sig));
*/

    // --------------------------------------------------------------

    // console.log('* * * * * * * * *'.yellow);
    // // Subkey succeeds in verifying with message 'hello world'
    // // echo -n 'hello world' | ./subkey verify <signature> 0x36838287ca3370224054f8a59ac79f112aac88e9adc39fd6b00d1e723e141a31
    // // signature can be passed with or without 0x
    // console.log('\nproduce signature for subkey verification - raw message'.bold);

    // let plainMessage = 'hello world';
    // let signer = keyring.addFromUri(signingKey);
    // let address = signer.address;
    // let signature = signer.sign(plainMessage)
    // console.log('Message'.yellow, plainMessage);
    // console.log('Signature of Plain Message', u8aToHex(signature));
    // console.log(`echo -n '${plainMessage}' | ./subkey verify ${u8aToHex(signature)} ${address}`.brightBlue.italic);

    /*
    console.log('* * * * * * * * *'.yellow);
    // Fails
    // Subkey does not understand encoded strings.
    // Encoded payload: 0x2c68656c6c6f20776f726c64
    // I tried with these, and all failed:
    // echo -n 0x2c68656c6c6f20776f726c64
    // echo -n '0x2c68656c6c6f20776f726c64'
    // echo -n 2c68656c6c6f20776f726c64
    // echo -n '2c68656c6c6f20776f726c64'
    console.log('produce signature for subkey verification - encoded message');
    signer = keyring.addFromUri(signingKey);
    signature = signer.sign(encodedPayload);
    console.log('Encoded payload'.yellow, encodedPayload);
    console.log('Signature', u8aToHex(signature));

    console.log('* * * * * * * * *'.yellow);
    // Fails
    // Subkey does not understand encoded strings.
    // Encoded payload: 0x2c68656c6c6f20776f726c64
    // I tried with these, and all failed:
    // echo -n 0x2c68656c6c6f20776f726c64
    // echo -n '0x2c68656c6c6f20776f726c64'
    // echo -n 2c68656c6c6f20776f726c64
    // echo -n '2c68656c6c6f20776f726c64'
    console.log('produce signature for subkey verification - encoded message minus 0x');
    signer = keyring.addFromUri(signingKey);
    signature = signer.sign(encodedPayload.slice(2));
    console.log('Encoded payload'.yellow, encodedPayload.slice(2));
    console.log('Signature', u8aToHex(signature));
*/

/*
    console.log('\n\n* * * * * * * * *'.bold.cyan);
    // Success
    // Subkey understands escaped sequences as bytes
    // Encoded payload: 0x2c68656c6c6f20776f726c64
    // Subkey input message: "\x2c\x68\x65\x6c\x6c\x6f\x20\x77\x6f\x72\x6c\x64"
    console.log('produce signature for subkey verification - encoded message minus 0x'.bold);
    signer = keyring.addFromUri(signingKey);
    let binaryPayload = u8aToHex(registry.createType('Text', plainMessage).toU8a(false));
    let bashPayload = hexToBashEscaped(binaryPayload);
    signature = signer.sign(binaryPayload);
    console.log('Encoded payload'.yellow, binaryPayload);
    console.log('Bash payload'.yellow, bashPayload);
    console.log('Signature', u8aToHex(signature));
    console.log(`echo -n -e '${bashPayload}' | ./subkey verify ${u8aToHex(signature)} ${address}`.brightBlue.italic);

    console.log('* * * * * * * * *'.yellow);

    console.log(`echo -n -e '${bashPayload}' | ./subkey sign --suri ${signingKey}`.brightRed.italic);
    let subkeySig = '0x70f91f427902e82b5d1afb8645983b343b23fd3c8cf5c9be91b7bb5f5df1944264168698be427a35c5f09750dbac1c2dd6609fac7f78d281bd80a8999d1ab58e';
    console.log(`message: ${bashPayload} `);

    wrapTest(verifyBytesSignature(binaryPayload, publicKey, subkeySig));
    wrapTest(verifyHexStringSignature(binaryPayload, publicKey, subkeySig));

    console.log('* * * * * * * * *'.gray.bold);
    console.log('Verifying CBAs latest data'.gray.bold);
*/

    // Summary so far:
    // Subkey takes its message and interprets it prima facie. It reads a text string, probably encodes it and signs.
    // It can verify strings that are signed in that way by us
    // But it can't understand when our raw data is encoded bytes. In this case, we pass a hex string representing an encoding
    // I believe in the backstate, we transform that into bytes and that is what we sign
    // I have not found how to pass 'bytes' to subkey
    console.log('Done');
}

// -------------------------------------------------------------------------
async function init(gateway) {
    let api = await avnApi(gateway)
    return api;
}

// Copied here form helper because that file is not ready to run with arguments in different order
// I want to specify the network to connect to, without having to put it in position 6 as
// helper.js currently requires
async function avnApi(gateway) {
    console.log('Connecting to Gateway at: ', gateway);
    const api = new AvnApi(gateway)
    await api.init()
    return api
}

function wrapTest(callResult) {
    console.log('* * * * * * * * *'.yellow);
    if (callResult) {
        console.log('Signature is ok'.green);
    } else {
        console.log('Signature is invalid'.red);
    }
    console.log('------------------\n'.yellow);
}

// Copied here because we can't import utils.js without axios, and we don't really need that here
function verifyAwtTokenSignature(publicKey, issuedAt, signature) {
    const encodedContext = registry.createType('Text', SIGNING_CONTEXT)
    const encodedPublicKey = registry.createType('AccountId', hexToU8a(publicKey))
    const encodedIssuedAt = registry.createType('Text', issuedAt)
    const encodedDataAsBytes = u8aConcat(
        encodedContext.toU8a(false),
        encodedPublicKey.toU8a(true),
        encodedIssuedAt.toU8a(false));

    return verifyBytesSignature(encodedDataAsBytes, publicKey, signature)
}

function verifyBytesSignature(encodedDataAsBytes, publicKey, signature) {
    return signatureVerify(u8aToHex(encodedDataAsBytes), signature, publicKey).isValid;
}

function verifyHexStringSignature(dataAsHexString, publicKey, signature) {
    return signatureVerify(dataAsHexString, signature, publicKey).isValid;
}

function hexToBashEscaped(string) {
    let chars = string.slice(2);
    let resultArray = [];
    for (let i = 0; i < chars.length; i+=2) {
        let pair = chars.slice(i, i + 2);
        resultArray.push(`\\x${pair}`);
    }

    let result = resultArray.join('');
    return result;
}

function bashEscapedToHex(string) {
    return '0x' + string.replace(/\\x/g, '');
}






( async () => {
    await main();
})().catch(err => {
    console.log(err)
});