apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- with .Values.ingress.additionalAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ .Chart.Name }}
    helmVersion: {{ .Chart.Version }}
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.ingress.domain }}"
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}