service: avn-gateway
package:
  individually: true
frameworkVersion: '3'

provider:
  region: ${file(./${env:SLS_ENV}.yml):region}
  name: aws
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::${file(./${env:SLS_ENV}.yml):avnVotesBucket}'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::${file(./${env:SLS_ENV}.yml):avnVotesBucket}/*'
        - Effect: Allow
          Action:
            - 'sqs:SendMessage'
            - 'sqs:SendMessageBatch'
            - 'sqs:ReceiveMessage'
            - 'sqs:DeleteMessage'
            - 'sqs:DeleteMessageBatch'
          Resource:
            - ${file(./${env:SLS_ENV}.yml):sqs_gateway_default_queue_arn}
            - ${file(./${env:SLS_ENV}.yml):sqs_gateway_payer_queue_arn}
  runtime: nodejs14.x
  versionFunctions: false
  logRetentionInDays: ${file(./${env:SLS_ENV}.yml):logRetentionDays}
  timeout: 6
  environment:
    AVN_CONNECTOR_ENDPOINT: ${file(./${env:SLS_ENV}.yml):avnConnectorEndpoint}
  httpApi:
    id: ${file(./${env:SLS_ENV}.yml):gatewayId}
  vpc:
    securityGroupIds:
      - Ref: LambdaSecurityGroup
    subnetIds:
      - ${file(./${env:SLS_ENV}.yml):subnet1}
      - ${file(./${env:SLS_ENV}.yml):subnet2}
      - ${file(./${env:SLS_ENV}.yml):subnet3}

layers:
  common:
    path: common
  queue:
    path: queue

functions:
  authorisation-handler:
    name: authorisation-handler
    handler: authorisation-handler.handler
    description: aws:states:opt-out
    environment:
      MAX_TOKEN_AGE_MSEC: ${file(./${env:SLS_ENV}.yml):maxTokenAgeMsec}
      MIN_AVT_BALANCE: ${file(./${env:SLS_ENV}.yml):minAvtBalance}
    package:
      patterns:
        - '!**/**'
        - authorisation-handler.js
    memorySize: 512
    layers:
      - { Ref: CommonLambdaLayer }

  poll-handler:
    name: poll-handler
    handler: poll-handler.handler
    description: aws:states:opt-out
    package:
      patterns:
        - '!**/**'
        - poll-handler.js
    memorySize: 256
    events:
      - httpApi:
          path: /poll
          method: POST
          authorizer:
            type: request
            id:
              Ref: Authorisation
    layers:
      - { Ref: CommonLambdaLayer }

  query-handler:
    name: query-handler
    handler: query-handler.handler
    description: aws:states:opt-out
    package:
      patterns:
        - '!**/**'
        - query-handler.js
    memorySize: 256
    events:
      - httpApi:
          path: /query
          method: POST
          authorizer:
            type: request
            id:
              Ref: Authorisation
    layers:
      - { Ref: CommonLambdaLayer }

  send-handler:
    name: send-handler
    handler: send-handler.handler
    description: aws:states:opt-out
    environment:
      MQ_AVN_TX_QUEUE: avnTx
      MQ_BROKER_AMQP_ENDPOINT: ${file(./${env:SLS_ENV}.yml):mqBrokerAmpqEndpoint}
      MQ_PROTOCOL: ${file(./${env:SLS_ENV}.yml):mqProtocol}
      MQ_SECRET_ARN: ${file(./${env:SLS_ENV}.yml):mqSecretArn}
      SECRET_MANAGER_REGION: ${aws:region}
      SQS_DEFAULT_QUEUE_URL: ${file(./${env:SLS_ENV}.yml):sqs_gateway_default_queue_url}
      SQS_PAYER_QUEUE_URL: ${file(./${env:SLS_ENV}.yml):sqs_gateway_payer_queue_url}
    package:
      patterns:
        - '!**/**'
        - send-handler.js
    memorySize: 512
    events:
      - httpApi:
          path: /send
          method: POST
          authorizer:
            type: request
            id:
              Ref: Authorisation
    layers:
      - { Ref: CommonLambdaLayer }
      - { Ref: QueueLambdaLayer }

  tx-status-update-handler:
    name: tx-status-update-handler
    handler: tx-status-update-handler.handler
    description: aws:states:opt-out
    environment:
      BLOCK_EXPLORER_BASE_URL: ${file(./${env:SLS_ENV}.yml):blockExplorerUrl}
    package:
      patterns:
        - '!**/**'
        - tx-status-update-handler.js
    memorySize: 128
    layers:
      - { Ref: CommonLambdaLayer }

  lift-processing-handler:
    name: lift-processing-handler
    handler: lift-processing-handler.handler
    description: aws:states:opt-out
    environment:
      MQ_AVN_TX_QUEUE: avnTx
      MQ_BROKER_AMQP_ENDPOINT: ${file(./${env:SLS_ENV}.yml):mqBrokerAmpqEndpoint}
      MQ_PROTOCOL: ${file(./${env:SLS_ENV}.yml):mqProtocol}
      MQ_SECRET_ARN: ${file(./${env:SLS_ENV}.yml):mqSecretArn}
      SECRET_MANAGER_REGION: ${aws:region}
    package:
      patterns:
        - '!**/**'
        - lift-processing-handler.js
    memorySize: 128
    layers:
      - { Ref: CommonLambdaLayer }
      - { Ref: QueueLambdaLayer }

  stakers-payout-handler:
    name: stakers-payout-handler
    handler: stakers-payout-handler.handler
    description: aws:states:opt-out
    environment:
      MQ_AVN_TX_QUEUE: avnTx
      MQ_BROKER_AMQP_ENDPOINT: ${file(./${env:SLS_ENV}.yml):mqBrokerAmpqEndpoint}
      MQ_PROTOCOL: ${file(./${env:SLS_ENV}.yml):mqProtocol}
      MQ_SECRET_ARN: ${file(./${env:SLS_ENV}.yml):mqSecretArn}
      SECRET_MANAGER_REGION: ${aws:region}
    package:
      patterns:
        - '!**/**'
        - stakers-payout-handler.js
    memorySize: 128
    layers:
      - { Ref: CommonLambdaLayer }
      - { Ref: QueueLambdaLayer }

  vote-handler:
    name: vote-handler
    handler: vote-handler.handler
    description: aws:states:opt-out
    environment:
      AVN_VOTES_BUCKET: ${file(./${env:SLS_ENV}.yml):avnVotesBucket}
    package:
      patterns:
        - '!**/**'
        - vote-handler.js
    memorySize: 256
    events:
      - httpApi:
          path: /vote
          method: ANY
    layers:
      - { Ref: CommonLambdaLayer }

  lower-handler:
    name: lower-handler
    handler: lower-handler.handler
    description: aws:states:opt-out
    timeout: 30
    package:
      patterns:
        - '!**/**'
        - lower-handler.js
    memorySize: 128
    events:
      - httpApi:
          path: /lowers
          method: GET

  split-fee-handler:
    name: split-fee-handler
    handler: split-fee-handler.handler
    description: aws:states:opt-out
    environment:
      SQS_PAYER_QUEUE_URL: ${file(./${env:SLS_ENV}.yml):sqs_gateway_payer_queue_url}
      SQS_DEFAULT_QUEUE_URL: ${file(./${env:SLS_ENV}.yml):sqs_gateway_default_queue_url}
      SECRET_MANAGER_REGION: ${aws:region}
    package:
      patterns:
        - '!**/**'
        - split-fee-handler.js
    memorySize: 128
    events:
      - sqs:
          arn: ${file(./${env:SLS_ENV}.yml):sqs_gateway_payer_queue_arn}
          functionResponseType: ReportBatchItemFailures
    layers:
      - { Ref: CommonLambdaLayer }
      - { Ref: QueueLambdaLayer }

  tx-dispatch-handler:
    name: tx-dispatch-handler
    handler: tx-dispatch-handler.handler
    description: aws:states:opt-out
    environment:
      MQ_AVN_TX_QUEUE: avnTx
      MQ_BROKER_AMQP_ENDPOINT: ${file(./${env:SLS_ENV}.yml):mqBrokerAmpqEndpoint}
      MQ_PROTOCOL: ${file(./${env:SLS_ENV}.yml):mqProtocol}
      MQ_SECRET_ARN: ${file(./${env:SLS_ENV}.yml):mqSecretArn}
      SECRET_MANAGER_REGION: ${aws:region}
      SQS_DEFAULT_QUEUE_URL: ${file(./${env:SLS_ENV}.yml):sqs_gateway_default_queue_url}
    package:
      patterns:
        - '!**/**'
        - tx-dispatch-handler.js
    memorySize: 128
    events:
      - sqs:
          arn: ${file(./${env:SLS_ENV}.yml):sqs_gateway_default_queue_arn}
          functionResponseType: ReportBatchItemFailures
    layers:
      - { Ref: CommonLambdaLayer }
      - { Ref: QueueLambdaLayer }

resources:
  Resources:
    LambdaSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupName: lambda-egress
        GroupDescription: Allow all outbound traffic, no inbound
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: 127.0.0.1/32
        VpcId: ${file(./${env:SLS_ENV}.yml):vpcId}
    Authorisation:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        Name: authorisation
        ApiId: ${file(./${env:SLS_ENV}.yml):gatewayId}
        AuthorizerPayloadFormatVersion: '2.0'
        AuthorizerResultTtlInSeconds: 60
        AuthorizerType: REQUEST
        AuthorizerUri: arn:aws:apigateway:${aws:region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${aws:region}:${file(./${env:SLS_ENV}.yml):awsAccount}:function:authorisation-handler/invocations
        EnableSimpleResponses: true
        IdentitySource:
          - $request.header.Authorization
    Permission:
      Type: AWS::Lambda::Permission
      DependsOn: AuthorisationDashhandlerLambdaFunction
      Properties:
        FunctionName: authorisation-handler
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub
          - arn:aws:execute-api:${aws:region}:${file(./${env:SLS_ENV}.yml):awsAccount}:${file(./${env:SLS_ENV}.yml):gatewayId}/authorizers/${AuthorizerId}
          - { AuthorizerId: !Ref Authorisation }
