service: avn-gateway
custom: ${file(./environments/${opt:env}.yml)}
package:
  individually: true
frameworkVersion: '2'

provider:
  region: ${self:custom.region}
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  logRetentionInDays: ${self:custom.log-retention-days}
  timeout: 6
  environment:
    AVN_CONNECTOR_ENDPOINT: ${self:custom.avn-connector-endpoint}
  httpApi:
    id: ${self:custom.gateway-id}
  vpc:
    securityGroupIds:
      - ${self:custom.security-group}
    subnetIds:
      - ${self:custom.subnet-1}
      - ${self:custom.subnet-2}
      - ${self:custom.subnet-3}

layers:
  common:
    path: common
  queue:
    path: queue

functions:
  authorisation-handler:
    name: authorisation-handler
    handler: authorisation-handler.handler
    description: aws:states:opt-out
    environment:
      MAX_TOKEN_AGE_MSEC: '60000'
      MIN_AVT_BALANCE: '100000000000000000000'
    package:
      patterns:
        - '!**/**'
        - authorisation-handler.js
    memorySize: 512
    layers:
      - Ref: CommonLambdaLayer

  poll-handler:
    name: poll-handler
    handler: poll-handler.handler
    description: aws:states:opt-out
    package:
      patterns:
        - '!**/**'
        - poll-handler.js
    memorySize: 256
    events:
      - httpApi:
          path: /poll
          method: POST
          authorizer:
            type: request
            id:
              Ref: Authorisation
    layers:
      - Ref: CommonLambdaLayer

  query-handler:
    name: query-handler
    handler: query-handler.handler
    description: aws:states:opt-out
    package:
      patterns:
        - '!**/**'
        - query-handler.js
    memorySize: 256
    events:
      - httpApi:
          path: /query
          method: POST
          authorizer:
            type: request
            id:
              Ref: Authorisation
    layers:
      - Ref: CommonLambdaLayer

  send-handler:
    name: send-handler
    handler: send-handler.handler
    description: aws:states:opt-out
    environment:
      MQ_AVN_TX_QUEUE: avnTx
      MQ_BROKER_AMQP_ENDPOINT: >-
        ${self:custom.mq-broker-ampq-endpoint}
      MQ_SECRET_ARN: arn:aws:secretsmanager:${self:custom.region}:${self:custom.aws-sso-id}:secret:rabbitmq
      SECRET_MANAGER_REGION: ${self:custom.region}
    package:
      patterns:
        - '!**/**'
        - send-handler.js
    memorySize: 512
    events:
      - httpApi:
          path: /send
          method: POST
          authorizer:
            type: request
            id:
              Ref: Authorisation
    layers:
      - Ref: CommonLambdaLayer
      - Ref: QueueLambdaLayer

  tx-status-update-handler:
    name: tx-status-update-handler
    handler: tx-status-update-handler.handler
    description: aws:states:opt-out
    environment:
      BLOCK_EXPLORER_BASE_URL: ${self:custom.block-explorer-url}
    package:
      patterns:
        - '!**/**'
        - tx-status-update-handler.js
    memorySize: 128
    layers:
      - Ref: CommonLambdaLayer

resources:
  Resources:
    Authorisation:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        Name: authorisation
        ApiId: ${self:custom.gateway-id}
        AuthorizerPayloadFormatVersion: '2.0'
        AuthorizerResultTtlInSeconds: 60
        AuthorizerType: REQUEST
        AuthorizerUri: >-
          arn:aws:apigateway:${self:custom.region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${self:custom.region}:${self:custom.aws-sso-id}:function:authorisation-handler/invocations
        EnableSimpleResponses: true
        IdentitySource:
          - $request.header.Authorization
    Permission:
      Type: AWS::Lambda::Permission
      DependsOn:
        - AuthorisationDashhandlerLambdaFunction
      Properties:
        FunctionName: authorisation-handler
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn:
          Fn::Sub:
            - >-
              arn:aws:execute-api:${self:custom.region}:${self:custom.aws-sso-id}:${self:custom.gateway-id}/authorizers/${AuthorizerId}
            - AuthorizerId:
              Ref: Authorisation
