service: avn-gateway

package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  versionFunctions: false
  timeout: 6
  environment:
    AVN_CONNECTOR_ENDPOINT: http://avn-connector.sandbox.aventus.internal:8080/
  httpApi:
    name: avn-gateway
    authorizers:
      awtAuthorisation:
        type: request
        functionName: awt
        resultTtlInSeconds: 60
        enableSimpleResponses: true
        identitySource: $request.header.Authorization
  logs:
    httpApi:
      format: '{"httpMethod":"$context.httpMethod","ip":"$context.identity.sourceIp","protocol":"$context.protocol","requestId":"$context.requestId","requestTime":"$context.requestTime","responseLength":"$context.responseLength","routeKey":"$context.routeKey","status":"$context.status"}'
  logRetentionInDays: 1
  vpc:
    securityGroupIds:
      - sg-036af2a870edc91ca
    subnetIds:
      - subnet-0fbd9b2001dd48ab2
      - subnet-02399a3c0dbbddfd9
      - subnet-0408c56e2665040d5

layers:
  common:
    path: common
  queue:
    path: queue

functions:
  awt:
    name: awt
    handler: awt.handler
    description: aws:states:opt-out
    environment:
      MAX_TOKEN_AGE_MSEC: 60000
      MIN_AVT_BALANCE: 100000000000000000000
    package:
      patterns:
        - '!**/**'
        - awt.js
    memorySize: 512
    layers:
      - { Ref: CommonLambdaLayer }

  poll:
    name: poll
    handler: poll.handler
    description: aws:states:opt-out
    package:
      patterns:
        - '!**/**'
        - poll.js
    memorySize: 256
    events:
      - httpApi:
          path: /poll
          method: POST
          authorizer:
            name: awtAuthorisation
    layers:
      - { Ref: CommonLambdaLayer }

  query:
    name: query
    handler: query.handler
    description: aws:states:opt-out
    package:
      patterns:
        - '!**/**'
        - query.js
    memorySize: 256
    events:
      - httpApi:
          path: /query
          method: POST
          authorizer:
            name: awtAuthorisation
    layers:
      - { Ref: CommonLambdaLayer }

  send:
    name: send
    handler: send.handler
    description: aws:states:opt-out
    environment:
      MQ_AVN_TX_QUEUE: avnTx
      MQ_BROKER_AMQP_ENDPOINT: amqps://b-46391450-1f8b-48a3-952a-856c35d7a44c.mq.eu-west-1.amazonaws.com:5671
      MQ_SECRET_ARN: arn:aws:secretsmanager:eu-west-1:352429414196:secret:rabbitmq-TU640D
      SECRET_MANAGER_REGION: eu-west-1
    package:
      patterns:
        - '!**/**'
        - send.js
    memorySize: 512
    events:
      - httpApi:
          path: /send
          method: POST
          authorizer:
            name: awtAuthorisation
    layers:
      - { Ref: CommonLambdaLayer }
      - { Ref: QueueLambdaLayer }

  tx-status-update:
    name: tx-status-update
    handler: tx-status-update.handler
    description: aws:states:opt-out
    environment:
      BLOCK_EXPLORER_BASE_URL: https://avn.stargate.aventus.io:3000
    package:
      patterns:
        - '!**/**'
        - tx-status-update.js
    memorySize: 128
    layers:
      - { Ref: CommonLambdaLayer }
