const AvnApi = require('../index.js');
const { accounts } = require('../config/accounts.json');
const BN = require('bn.js');
const { hexAddPrefix, hexToU8a, u8aToHex, u8aConcat } = require('@polkadot/util');
var colors = require('colors');
const { TypeRegistry } = require('@polkadot/types');
const { signatureVerify, cryptoWaitReady } = require('@polkadot/util-crypto');
const { Keyring } = require('@polkadot/keyring');
const { assert, expect } = require('chai');
const keyring = new Keyring({ type: 'sr25519', ss58Format: 42 });
const prompt = require('prompt-sync')({ sigint: true });

const registry = new TypeRegistry();
const SIGNING_CONTEXT = 'awt_gateway_api';
const SEPARATOR = '--------------------------------------------------------------------------';

const cbaSet = {
  bashBinary:
    '\\x3c\\x61\\x77\\x74\\x5f\\x67\\x61\\x74\\x65\\x77\\x61\\x79\\x5f\\x61\\x70\\x69\\xd0\\xbc\\x96\\x2a\\xc2\\x1f\\xb7\\x4c\\xc5\\x08\\x2f\\x24\\xda\\x62\\x26\\x0d\\xc0\\xd4\\x1c\\x12\\x82\\xce\\x46\\xcc\\xef\\xac\\xa6\\xed\\xc5\\xf0\\x0b\\x49\\x60\\x32\\x30\\x32\\x32\\x2d\\x30\\x31\\x2d\\x31\\x30\\x54\\x31\\x36\\x3a\\x30\\x30\\x3a\\x35\\x38\\x2e\\x38\\x35\\x39\\x5a',
  pk: '0xd0bc962ac21fb74cc5082f24da62260dc0d41c1282ce46ccefaca6edc5f00b49',
  iat: '2022-01-10T16:00:58.859Z',
  sig: '0xb07ea03c16ee31d37d9e109cf15bd0aaf8654f51429660565dda52eb516cf24a6343efa76907850d57c5d3baf54bd300c8efad7c0b9249aae7536ee8e9bde081'
};

async function main() {
  await cryptoWaitReady(); // This is essential for successful verification of signatures

  // Comment or uncomment to run specific tests as needed:

  await demoCbaAwt();
  testSCALEEncoding();
  testCBASignature();
  testSubkeyCompatibility();
}

async function demoCbaAwt() {
  // Run this script with node ./testTools.js <config file name without extension>
  // If you get an error at startup similar to this
  // TypeError: Cannot read property 'startsWith' of undefined
  // it may be because you have not defined your AVN_SURI environment variable
  console.log(SEPARATOR.blue.bold);
  console.log('Verifying Awt token generation by the api with custom time'.bold);
  console.log(SEPARATOR.blue.bold);
  let args = process.argv.slice(2);
  let configPath = args[0] ? `../config/${args[0]}.json` : '../config/sandbox.json';
  const { gateway } = require(configPath);

  let user = accounts.cbaTestAccount;
  let api = await init(gateway);

  let iat = cbaSet.iat;
  let pk = user.publicKey;

  let sigPayload = api.awt.encodeAvnPublicKeyForSigning(pk, iat);
  console.log('\nAwt Signature: Public Key\n'.blue.bold, pk);
  console.log('\nAwt Signature: Encoded Payload\n'.blue.bold, sigPayload);

  let payload = api.awt.generateAwtPayload(user.mnemonic, iat);
  let myToken = await api.awt.generateAwtTokenFromPayload(payload);
  console.log('\nAwt Signature: Raw Payload\n'.blue.bold, payload);
  console.log('\nAwt Token:'.blue.bold, myToken);

  console.log('Verifying signature of AwtToken generated by the API'.yellow);
  wrapTest(verifyAwtTokenSignature(payload.pk, payload.iat, payload.sig));
}

function testSCALEEncoding() {
  console.log(SEPARATOR.brightCyan);
  console.log('Demonstrate creation of a binary encoding of an ASCII payload'.bold);
  console.log(SEPARATOR.brightCyan);
  let text1 = 'hello world';
  let text2 = 'hix';

  const payload = u8aConcat(registry.createType('Text', text1).toU8a(false), registry.createType('Text', text2).toU8a(false));

  console.log('\nEncoded Payload Test\n'.brightCyan, `${u8aToHex(payload)}`);
}

function testCBASignature() {
  console.log('\n');
  console.log(SEPARATOR.brightMagenta);
  console.log('Verifying Signature created by CBA (using Subkey)'.bold);
  console.log(SEPARATOR.brightMagenta);

  let cbaEncodedData;
  if (cbaSet.bashBinary) {
    cbaEncodedData = bashEscapedToHex(cbaSet.bashBinary);
    console.log('\nReconstructed Hex String binary payload'.brightMagenta, cbaEncodedData);
  } else {
    cbaEncodedData = cbaSet.encodedData;
    console.log('\nOriginal Hex String binary payload'.brightMagenta, cbaEncodedData);
  }

  let awtToken = {
    pk: cbaSet.pk,
    iat: cbaSet.iat,
    sig: cbaSet.sig
  };

  console.log('Checking signature from AwtToken'.yellow);
  wrapTest(verifyAwtTokenSignature(awtToken.pk, awtToken.iat, awtToken.sig));

  console.log('Checking signature from HexString encoded data'.yellow);
  wrapTest(verifyHexStringSignature(cbaEncodedData, awtToken.pk, awtToken.sig));
}

async function testSubkeyCompatibility() {
  await cryptoWaitReady();

  console.log('\n');
  console.log(SEPARATOR.brightCyan);
  console.log('Verifying Subkey compatibility of generated signatures'.bold);
  console.log(SEPARATOR.brightCyan);

  let signingKey = '0x81cd713ef51940a684b5db9c36dcafc3199b6bdff4b2c332f9fc88a3f69c0881';
  let signer = keyring.addFromUri(signingKey);
  let publicKey = signer.publicKey;
  let address = signer.address;

  let plainMessage = 'hello world';
  let messageAsBytes = u8aToHex(registry.createType('Text', plainMessage).toU8a(false));

  console.log('Signature of ascii data for Subkey'.brightCyan);
  let signature = signer.sign(plainMessage);
  wrapTest(verifyHexStringSignature(plainMessage, publicKey, signature));

  console.log('Please, verify in Subkey with these commands'.brightCyan);
  console.log(`\necho -n '${plainMessage}' | ./subkey verify ${u8aToHex(signature)} ${u8aToHex(publicKey)}`.gray.italic);
  console.log(`\necho -n '${plainMessage}' | ./subkey verify ${u8aToHex(signature)} ${address}`.gray.italic);

  console.log('Signature of binary data for Subkey'.brightCyan);
  signature = signer.sign(messageAsBytes);
  wrapTest(verifyHexStringSignature(messageAsBytes, publicKey, signature));
  let bashPayload = hexToBashEscaped(messageAsBytes);

  console.log('Please, verify in Subkey with these commands'.brightCyan);
  console.log(
    `\necho -n -e '${bashPayload}' | ./subkey verify ${u8aToHex(signature)} ${u8aToHex(publicKey)}`.blue.italic.bgBrightYellow
  );
  console.log(`\necho -n -e '${bashPayload}' | ./subkey verify ${u8aToHex(signature)} ${address}`.blue.italic.bgBrightYellow);
  console.log('\n');
  // --------------------------------------------------------------

  console.log('Creation of ascii signature in Subkey and verification in Polkadot'.brightCyan);
  console.log(`echo -n '${plainMessage}' | ./subkey sign --suri ${signingKey}`.bgBrightWhite.italic.red);
  let subkeySig = prompt('Enter Subkey-generated signature: ');
  subkeySig = hexAddPrefix(subkeySig);
  console.log(`Signature: ${subkeySig} `.yellow);
  wrapTest(verifyHexStringSignature(plainMessage, publicKey, subkeySig));

  console.log('Creation of binary signature in Subkey and verification in Polkadot'.brightCyan);
  console.log(`echo -n -e '${bashPayload}' | ./subkey sign --suri ${signingKey}`.bgBrightWhite.italic.red);
  subkeySig = prompt('Enter Subkey-generated signature: ');
  subkeySig = hexAddPrefix(subkeySig);
  console.log(`Signature: ${subkeySig} `.yellow);

  wrapTest(verifyHexStringSignature(messageAsBytes, publicKey, subkeySig));
}

// -------------------------------------------------------------------------
async function init(gateway) {
  let api = await avnApi(gateway);
  return api;
}

// Copied here form helper because that file is not ready to run with arguments in different order
// I want to specify the network to connect to, without having to put it in position 6 as
// helper.js currently requires
async function avnApi(gateway) {
  console.log('Connecting to Gateway at: ', gateway);
  const api = new AvnApi(gateway);
  await api.init();
  return api;
}

function wrapTest(callResult) {
  console.log('* * * * * * * * *'.yellow);
  if (callResult) {
    console.log('Signature is ok'.green);
  } else {
    console.log('Signature is invalid'.red);
  }
  console.log('------------------\n'.yellow);
}

// Copied here because we can't import utils.js without axios, and we don't really need that here
function verifyAwtTokenSignature(publicKey, issuedAt, signature) {
  const encodedContext = registry.createType('Text', SIGNING_CONTEXT);
  const encodedPublicKey = registry.createType('AccountId', hexToU8a(publicKey));
  const encodedIssuedAt = registry.createType('Text', issuedAt);
  const encodedDataAsBytes = u8aConcat(encodedContext.toU8a(false), encodedPublicKey.toU8a(true), encodedIssuedAt.toU8a(false));

  return verifyBytesSignature(encodedDataAsBytes, publicKey, signature);
}

function verifyBytesSignature(encodedDataAsBytes, publicKey, signature) {
  return signatureVerify(u8aToHex(encodedDataAsBytes), signature, publicKey).isValid;
}

function verifyHexStringSignature(dataAsHexString, publicKey, signature) {
  return signatureVerify(dataAsHexString, signature, publicKey).isValid;
}

function hexToBashEscaped(string) {
  let chars = string.slice(2);
  let resultArray = [];
  for (let i = 0; i < chars.length; i += 2) {
    let pair = chars.slice(i, i + 2);
    resultArray.push(`\\x${pair}`);
  }

  let result = resultArray.join('');
  return result;
}

function bashEscapedToHex(string) {
  return '0x' + string.replace(/\\x/g, '');
}

(async () => {
  await main();
})().catch(err => {
  console.log(err);
});
