secretManagerRegion: [AWS region eg. eu-west-2]
mqSecretArn: [AWS Secret Manager Secret ARN, eg. arn:aws:secretsmanager:{aws_region}:0123456789:secret:{ABCDEFG-012Abc}]
mqBrokerAmqpEndpoint: [AWS RabbitMQ Broker Amqp Endpoint, eg. amqps://x-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.mq.{aws_region}.amazonaws.com:5671]
components:
  avnTxQueue: [A queue name to consume messages from, eg. avnTx]
  avnTxRetryCount: [Number of retry to send a previously failed transaction to AVN, eg. 3]
  avnTxRetryDelay: [Number of milliseconds to delay before each retry, eg. 1000]
  deadLetterQueue: [A dead letter queue name to store TTL timeout, negative acknowledged messages from other queue, eg. dlq_queue]
  deadLetterExchange: [A dead letter exchange name to redirect dead letter messages to the dead letter queue, eg. dlx_exchange]
  deadLetterKey: [A key used by an exchange to forward dead letter messages to the dead letter queue, eg. dlx_key]