apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
spec:
  backendType: secretsManager
  data:
    - key: rabbitmq
      name: rabbitmq-password
      property: password