environment: cba
nodeEnv: docker
accountId: "352429414196"

deployment:
  image:
    repo: 189013141504.dkr.ecr.eu-west-2.amazonaws.com/gateway-api/avn-connector
    tag: latest
    pullPolicy: Always

  server:
    port: 5000

  replicas: 1
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 20%

  resources: {}

service:
  type: ClusterIP
  port: 8080

  subnetIds: ""
