avnUrl: $ENV:AVN_NODE_URL
# Todo: Remove "avnUrl_old" - temporary parallel path for voting
avnUrl_old: $ENV:AVN_NODE_URL_old
serverPort: $ENV:SERVER_PORT
stakingPayoutRelayer: $ENV:STAKING_PAYOUT_RELAYER