environment: sandbox

rabbitmq:
  image:
    tag: "3.8.22"

  auth:
    existingPasswordSecret: rabbitmq-credentials
    username: lambda

  ingress:
    # We disable the internal ingress and use our own templated ingress instead
    # This gives us annotations that are easily changed via the environment that we are
    # deploying into rather than have our pipelines modify the ingress with externaldns annotations
    enabled: false

  replicaCount: 1