aws-load-balancer-controller:
  clusterName: avn-gateway

  podAnnotations:
    fluentbit.io/exclude: "true"

  serviceAccount:
    # use pregenerated serviceaccount
    create: false
    name: aws-load-balancer-controller
