name: avn-connector

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - ew-main-hotfix-b830ec7

defaults:
  run:
    shell: bash

jobs:
  ew-docker-connector:
    name: (EW) build docker connector
    uses: ./.github/workflows/docker-build.yaml
    with:
      runner: avn-runner
      config_creds: false
      aws_region: us-east-1
      aws_account_id: 541507968610
      context: avn-connector
      short_image_name: connector
      ecr_repository_prefix: gateway
