name: avn-connector

on:
  pull_request:
    branches:
      - main
    paths:
      - 'avn-connector/**'
  push:
    branches:
      - main
    paths:
      - 'avn-connector/**'

defaults:
  run:
    shell: bash
    working-directory: avn-connector

jobs:
  connector:
    runs-on: ubuntu-latest
    name: package avn-connector image
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Create tag for PR
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create tag for merge
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=${GITHUB_SHA::7},latest" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        # save registry URL in env
      - run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: whoan/docker-build-with-cache-action@v5
        env:
          SHORT_IMAGE_NAME: avn-connector
          ECR_REPOSITORY_PREFIX: gateway-api
        with:
          image_name: ${{ env.ECR_REPOSITORY_PREFIX }}/${{ env.SHORT_IMAGE_NAME }}
          stages_image_name: ${{ env.ECR_REPOSITORY_PREFIX }}/${{ env.SHORT_IMAGE_NAME }}-stages
          push_git_tag: true
          image_tag: ${{ env.DOCKER_TAG }}
          registry: ${{ env.ECR_REGISTRY }}
          context: avn-connector/
          build_extra_args: --compress=true
  
  add-relayer:
    runs-on: ubuntu-latest
    name: package addRelayer init container
    steps:
      - uses: actions/checkout@v2

      - name: Create tag for PR
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create tag for merge
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=${GITHUB_SHA::7},latest" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        # save registry URL in env
      - run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: whoan/docker-build-with-cache-action@v5
        env:
          SHORT_IMAGE_NAME: relayer-account
          ECR_REPOSITORY_PREFIX: gateway-api
        with:
          image_name: ${{ env.ECR_REPOSITORY_PREFIX }}/${{ env.SHORT_IMAGE_NAME }}
          stages_image_name: ${{ env.ECR_REPOSITORY_PREFIX }}/${{ env.SHORT_IMAGE_NAME }}-stages
          push_git_tag: true
          image_tag: ${{ env.DOCKER_TAG }}
          registry: ${{ env.ECR_REGISTRY }}
          context: avn-connector/
          build_extra_args: --compress=true
          dockerfile: Dockerfile.addrelayer
  
  insert-fees:
    runs-on: ubuntu-latest
    name: package insertFees init container
    steps:
      - uses: actions/checkout@v2

      - name: Create tag for PR
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create tag for merge
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=${GITHUB_SHA::7},latest" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        # save registry URL in env
      - run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: whoan/docker-build-with-cache-action@v5
        env:
          SHORT_IMAGE_NAME: relayer-fees
          ECR_REPOSITORY_PREFIX: gateway-api
        with:
          image_name: ${{ env.ECR_REPOSITORY_PREFIX }}/${{ env.SHORT_IMAGE_NAME }}
          stages_image_name: ${{ env.ECR_REPOSITORY_PREFIX }}/${{ env.SHORT_IMAGE_NAME }}-stages
          push_git_tag: true
          image_tag: ${{ env.DOCKER_TAG }}
          registry: ${{ env.ECR_REGISTRY }}
          context: avn-connector/
          build_extra_args: --compress=true
          dockerfile: Dockerfile.inserttestfees