name: Build and Push artifacts to Energy Web

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker-connector:
    name: build docker connector
    uses: ./.github/workflows/docker-build.yaml
    with:
      runner: avn-runner-ubuntu-2204-x64
      config_creds: false
      aws_region: us-east-1
      aws_account_id: 541507968610
      context: avn-connector
      short_image_name: connector
      ecr_repository_prefix: gateway
  
  package:
    runs-on: ubuntu-latest
    name: package lambda functions
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Package Function manual build
        if: ${{ !startsWith(github.event.ref, 'refs/tags/v') }}
        run: make package version=${GITHUB_SHA::7}

      - name: Package Function release
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: make package version=${GITHUB_REF#refs/*/}

      - name: Upload lambdas to cache
        uses: actions/upload-artifact@v3
        with:
          name: avn-gateway
          path: avn-gateway/build/

  upload:
    runs-on: avn-runner-ubuntu-2404-x64
    needs:  [ package ]
    name: Upload lambdas to AVN internal-tools s3 bucket
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: avn-gateway
        path: avn-gateway/build/

    - name: Upload to S3
      run: |
        aws s3 sync build/. s3://ewx-internal-artefact/gateway-lambdas --acl bucket-owner-full-control

  cleanup-artifacts:
    runs-on: ubuntu-latest
    needs:  [upload]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: avn-gateway
        
